### ISSUE TITLE
/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 64, in _load_javascript raise Exception('Signature function not found')

### ISSUE THREAD

**Issue by criterion9** [jdf76/plugin.video.youtube#424]
I started getting an error today and no videos seems to be working through the plugin.

**Comment by anxdpanic** [comment]
Yea, youtube has changed something. Need to look further into it

**Comment by anxdpanic** [comment]
Issue is fixed in [6.1.4](https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.4) and [6.2.0-dev](https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.0-dev)
Also a thank you @Twilight0

**Comment by criterion9** [comment]
Out of curiosity, is this plugin update available from a repo so it updates automatically going forward?

**Comment by anxdpanic** [comment]
Currently only through the official repo. The fix has been submitted to the official repo already just awaiting review.

**Comment by syagev** [comment]
Confirmed to be resolved by an update to 6.1.4 via the official repo
Thanks!

**Comment by spirgiuz** [comment]
Thanks, this fixed most of the videos that didn't open before, but I found one video that still doesn't open for me with 6.1.4. I'm not sure if it's related to this or a separate problem: https://www.youtube.com/watch?v=mPzVPdiW1wE
