### ISSUE TITLE
YouTubeException: No streams found

### ISSUE THREAD

**Issue by madcowchow** [jdf76/plugin.video.youtube#819]
Hi

Please help, getting the following since this morning, tried the alpha version too. Thanks
````
2020-05-07 10:45:22.639 T:1427370720  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.1~alpha1) on Leia (Kodi-18.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': '9SICD7pjvOs'}
2020-05-07 10:45:28.087 T:1427370720   ERROR: Traceback (most recent call last):
2020-05-07 10:45:28.087 T:1427370720   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
2020-05-07 10:45:28.088 T:1427370720   ERROR:     video_streams = client.get_video_streams(context, video_id)
2020-05-07 10:45:28.088 T:1427370720   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
2020-05-07 10:45:28.089 T:1427370720   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
2020-05-07 10:45:28.089 T:1427370720   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
2020-05-07 10:45:28.089 T:1427370720   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
2020-05-07 10:45:28.090 T:1427370720   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1049, in _method_get_video_info
2020-05-07 10:45:28.090 T:1427370720   ERROR:     raise YouTubeException('No streams found')
2020-05-07 10:45:28.091 T:1427370720   ERROR: YouTubeException: No streams found


2020-05-07 10:47:22.134 T:1686098656  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.0) on Leia (Kodi-18.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'LBXbn0AysrU'}
2020-05-07 10:47:27.706 T:1686098656   ERROR: Traceback (most recent call last):
2020-05-07 10:47:27.706 T:1686098656   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
2020-05-07 10:47:27.708 T:1686098656   ERROR:     video_streams = client.get_video_streams(context, video_id)
2020-05-07 10:47:27.708 T:1686098656   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
2020-05-07 10:47:27.712 T:1686098656   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
2020-05-07 10:47:27.712 T:1686098656   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
2020-05-07 10:47:27.717 T:1686098656   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
2020-05-07 10:47:27.718 T:1686098656   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1049, in _method_get_video_info
2020-05-07 10:47:27.719 T:1686098656   ERROR:     raise YouTubeException('No streams found')
2020-05-07 10:47:27.719 T:1686098656   ERROR: YouTubeException: No streams found
2020-05-07 10:47:27.719 T:1686098656   ERROR: [plugin.video.youtube] None
````

**Comment by NaotoNomura** [comment]
```
2020-05-07 08:01:45.956 T:2690121984  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.0) on Leia (Kodi-18.6) with Python 2.7.18
                                            	Path: /play/
                                            	Params: {'video_id': 'ynON9o2yHVk'}
2020-05-07 08:01:47.857 T:2690121984   ERROR: Traceback (most recent call last):
2020-05-07 08:01:47.857 T:2690121984   ERROR:   File "/home/alarm/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
2020-05-07 08:01:47.857 T:2690121984   ERROR:     video_streams = client.get_video_streams(context, video_id)
2020-05-07 08:01:47.857 T:2690121984   ERROR:   File "/home/alarm/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
2020-05-07 08:01:47.858 T:2690121984   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
2020-05-07 08:01:47.858 T:2690121984   ERROR:   File "/home/alarm/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
2020-05-07 08:01:47.859 T:2690121984   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
2020-05-07 08:01:47.859 T:2690121984   ERROR:   File "/home/alarm/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1049, in _method_get_video_info
2020-05-07 08:01:47.859 T:2690121984   ERROR:     raise YouTubeException('No streams found')
2020-05-07 08:01:47.859 T:2690121984   ERROR: YouTubeException: No streams found
2020-05-07 08:01:47.859 T:2690121984   ERROR: [plugin.video.youtube] None
2020-05-07 08:01:47.874 T:2977090336   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=ynON9o2yHVk]
```
Same issue

**Comment by NaotoNomura** [comment]
Made a fix

```
--- addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py	2020-05-07 09:17:42.730809039 +0000
+++ addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py.fix	2020-05-07 09:17:30.361028325 +0000
@@ -688,7 +688,10 @@
             fl = []
             if len(_fmts) > 0:
                 try:
-                    fl = _fmts[0].get('cipher').split(',')
+                    if 'cipher' in _fmts[0]:
+                        fl = _fmts[0].get('cipher').split(',')
+                    else:
+                        fl = _fmts[0].get('signatureCipher').split(',')
                 except AttributeError:
                     fl = _fmts[0].get('url', '').split('&')
             return (len(fl) > 0) and ('s' in dict(urllib.parse.parse_qsl(fl[0])))
@@ -985,7 +988,10 @@
         def parse_to_stream_list(streams):
             for item in streams:
                 stream_map = item
-                stream_map.update(dict(urllib.parse.parse_qsl(item.get('cipher', ''))))
+                if 'cipher' in stream_map:
+                    stream_map.update(dict(urllib.parse.parse_qsl(item.get('cipher', ''))))
+                else:
+                    stream_map.update(dict(urllib.parse.parse_qsl(item.get('signatureCipher', ''))))
 
                 url = stream_map.get('url', None)
                 conn = stream_map.get('conn', None)
```
I will make pull request, but now you can copy this patch or download it from [here](https://gist.github.com/NaotoNomura/c23381d1a1423faf439e656f6d4e6275). Place it in your `.kodi` directory and run:
```
patch -p0 < fix.patch
```

**Comment by NaotoNomura** [comment]
It is fixed [here](https://github.com/jdf76/plugin.video.youtube/commit/a58d2bbd2b15068f1562a852ea65d15217e276b4) as i see.

**Comment by anxdpanic** [comment]
This is fixed in alpha1, zips can be found: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by madcowchow** [comment]
Thanks all. all working now.

**Comment by madcowchow** [comment]
closing

**Comment by newtokodi** [comment]
Hi, I am still having this issue with 6.8.1.alpha1.


```
14:19:32.676 T:18446744073018014000   ERROR: Traceback (most recent call last):
14:19:32.676 T:18446744073018014000   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
14:19:32.677 T:18446744073018014000   ERROR:     video_streams = client.get_video_streams(context, video_id)
14:19:32.678 T:18446744073018014000   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
14:19:32.681 T:18446744073018014000   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
14:19:32.681 T:18446744073018014000   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
14:19:32.685 T:18446744073018014000   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
14:19:32.685 T:18446744073018014000   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1049, in _method_get_video_info
14:19:32.686 T:18446744073018014000   ERROR:     raise YouTubeException('No streams found')
14:19:32.686 T:18446744073018014000   ERROR: YouTubeException: No streams found
14:19:32.686 T:18446744073018014000   ERROR: [plugin.video.youtube] None
14:19:32.687 T:18446744073018014000   DEBUG: [plugin.video.youtube] Shutdown of Kodion after |2.5753| seconds
14:19:32.687 T:18446744073018014000    INFO: CPythonInvoker(21, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
14:19:32.689 T:18446744073010936112   DEBUG: Thread scriptobs 18446744073010936112 terminating
14:19:32.690 T:18446744073508206896   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=ZwGgVp5N0_A]
```

**Comment by newtokodi** [comment]
I am still facing the same issue with alpha2. Should I create a new issue?

**Comment by madcowchow** [comment]
Hi, try uninstalling the plugin completely delete the plugin folder from .kodi/addons/plugin.video.youtube then reinstall from the repo (YouTube (6.8.0)). be sure to backup your api key settings.

**Comment by newtokodi** [comment]
Reinstalled but still the same issue.

**Comment by madcowchow** [comment]
reopeneing issue for newtokodi. the fix here seems to have worked for me.

**Comment by anxdpanic** [comment]
@newtokodi 
Can you provide a debug log and a video id for an example video that's not working.
A walk-through for obtaining a log can be found https://kodi.wiki/view/Log_file

**Comment by anxdpanic** [comment]
6.8.1 is waiting review on the official repository, release available: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.8.1


@newtokodi Please re-open with a debug log if the issue persists.

**Comment by newtokodinewacc** [comment]
Hi, sorry for the delayed response. The issue still persists. Here is a debug log for a fresh install:
https://paste.kodi.tv/owisaqafur.kodi

**Comment by newtokodinewacc** [comment]
I tried the addon on Kodi for Mac and it works properly with the same API keys and on the same network. 
Seems to be a device specific issue. I am having the issue on a MiTV 4A.

**Comment by newtokodinewacc** [comment]
Hi @anxdpanic, there seems to be a problem in getting the watch page itself. Seems YT is blocking the request. Here is the HTML page that gets received in https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/video_info.py#L714
https://paste.kodi.tv/raw/rinuwasilo

It's strange that everything works properly on a different device. If I simply set the video_streams in yt_play.py#L50 to the ones that's received on the different device, the video plays fine.

**Comment by anxdpanic** [comment]
@newtokodinewacc 

If you use Switch User to test a logged out user and it still doesn't work can you try changing

https://github.com/jdf76/plugin.video.youtube/blob/284c7d105514b82dc450f0d145f752596329be45/resources/lib/youtube_plugin/youtube/helper/video_info.py#L606
to
```python
page_result = self.get_watch_page(video_id)
```
and see if that works when not logged in, thanks!

**Comment by newtokodinewacc** [comment]
@anxdpanic 
It did work when I switched to a logged out user. I tried re-installing but it still works as of now. I will give it a try once again and let you know.

**Comment by newtokodinewacc** [comment]
@anxdpanic 
It did work when I switched to a logged out user. I tried re-installing but it still works as of now.
But I doubt that it would work. Last time while I was testing, adaptive_fmts and std_fmts were both empty so get_player_js shouldn't get called at all, but I could be wrong.
I will give it a try once again and let you know.
